### ISSUE TITLE
Post effective method of file upload on mongo atlas using nodejs

### ISSUE THREAD

**Issue by mostlypanda** [mostlypanda/Node-js-functionalities#17]
Anyone wants to work

**Comment by amandugar** [comment]
Can you explain

**Comment by mostlypanda** [comment]
Ya sure, listen you have to simply make a rest API in nodejs for file upload to mongo atlas so that it can be use anywhere

**Comment by codiiyapaa** [comment]
I want to work on this.

**Comment by mostlypanda** [comment]
Well paras I have resolved this but if you want to work on this go for it. I will incorporate your changes too in this repo

**Comment by codiiyapaa** [comment]
Okay! Thankyou.
